# Generated by Django 3.1.7 on 2021-05-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlcss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprajo',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
